# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle and Docker - Merge Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - .github/workflows/*

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import Vault Secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/com-shankarsan artifactory-url | ARTIFACTORY_URL ;
            secret/data/com-shankarsan artifactory-username | ARTIFACTORY_USERNAME ;
            secret/data/com-shankarsan artifactory-password | ARTIFACTORY_PASSWORD ;
            secret/data/com-shankarsan docker-hub-token | DOCKER_HUB_TOKEN ;
            secret/data/com-shankarsan sonar-token | SONAR_TOKEN ;
            secret/data/com-shankarsan sonar-host-url | SONAR_HOST_URL ;
            secret/data/utility-scheduler ssl-keystore-base64 | SSL_KEYSTORE_BASE64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Docker Hub Login
        uses: docker/login-action@v3.1.0
        with:
          username: shankershawn
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - uses: actions/checkout@v4.1.6
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache SonarQube packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Generate SSL keystore file
        shell: bash
        run: |
          base64 -d ${{ env.SSL_KEYSTORE_BASE64 }} > src/main/resources/keystore.jks
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build
        env:
          GITHUB_VERSION: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
      - name: Sonarqube Scan
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        env:
          GITHUB_VERSION: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
        with:
          arguments: sonar --stacktrace
      - name: Publish to Sonatype
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        env:
          GITHUB_VERSION: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
        with:
          arguments:
            publish
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            RUN_NUMBER=${{ github.run_number }}
          tags: shankershawn/utility-scheduler:${{ github.sha }},shankershawn/utility-scheduler:latest
