# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle and Docker - PR Build

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - .github/workflows/*

permissions:
  contents: read

jobs:
  setup:
    runs-on: raspberrypi
    steps:
      - name: Install libatomic
        run: sudo apt-get update -y && sudo apt-get install libatomic1
      - name: Import Vault Secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: http://144.24.128.195:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/com-shankarsan artifactory-url | ARTIFACTORY_URL ;
            secret/data/com-shankarsan artifactory-username | ARTIFACTORY_USERNAME ;
            secret/data/com-shankarsan artifactory-password | ARTIFACTORY_PASSWORD ;
            secret/data/com-shankarsan sonar-token | SONAR_TOKEN ;
            secret/data/com-shankarsan sonar-host-url | SONAR_HOST_URL
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Code checkout
        uses: actions/checkout@v4.1.6
  build-and-test:
    runs-on: raspberrypi
    needs:
      - setup
    steps:
      - name: Build with Gradle
        #uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        #with:
          #arguments: clean build -x sonar
        run: ./gradlew clean build -x sonar
        env:
          GITHUB_VERSION: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
  sonar-scan:
    runs-on: raspberrypi
    needs:
      - build-and-test
    steps:
      - name: Sonarqube Scan
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        run: ./gradlew sonar
        env:
          GITHUB_VERSION: ${{ github.sha }}
          RUN_NUMBER: ${{ github.run_number }}
#        with:
#          arguments: sonar --stacktrace
  docker-build:
    runs-on: raspberrypi
    needs:
      - sonar-scan
    steps:
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: false
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            RUN_NUMBER=${{ github.run_number }}
          tags: shankershawn/utility-scheduler:${{ github.sha }},shankershawn/utility-scheduler:latest
